Website1/Models/ErrorViewModel.cs
namespace Website1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Website1/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Website1.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

Website1/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Website1.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Submit(string name, string email, string message)
        {
            if (string.IsNullOrEmpty(name))
            {
                ModelState.AddModelError("Name", "Name is required.");
            }
            if (string.IsNullOrEmpty(email))
            {
                ModelState.AddModelError("Email", "Email is required.");
            }
            if (string.IsNullOrEmpty(message))
            {
                ModelState.AddModelError("Message", "Message is required.");
            }

            // If there are validation errors, return the view with errors
            if (!ModelState.IsValid)
            {
                return View("Contact");
            }

            TempData["SuccessMessage"] = "Thank you for your submission! We have received your message.";

            // Render the original view with the popup message
            return RedirectToAction("Contact");

        }
    }
}

Website1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Website1.Models;

namespace Website1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //login view+ Function
        public IActionResult Login()
        {
            return View();
        }

        //For register 
        public IActionResult Register()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Website1/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace Website1.Controllers
{
    public class ServiceController : Controller
    {
        public IActionResult Service()
        {
            return View();
        }

        public IActionResult ViewCard()
        {
            return View();
        }
    }
}

Website1/Views/About/About.cshtml
@{
    ViewData["Title"] = "About";
}

<!-- About 1 - Bootstrap Brain Component -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/Style.css" />
</head>
<body>
    <style>
        .about{
            margin-top: 50px;
        }
    </style>
<section class="about">
<section class="py-3 py-md-5">
    <div class="container">
        <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
            <div class="col-12 col-lg-6 col-xl-5">
                <img class="img-fluid rounded" loading="lazy" src="~/Images/image2..png" alt="About 1">
            </div>
            <div class="col-12 col-lg-6 col-xl-7">
                <div class="row justify-content-xl-center">
                    <div class="col-12 col-xl-11">
                        <h2 class="mb-3">Who Are We?</h2>
                        <p class="lead fs-4 text-secondary mb-3">We help people to build incredible brands and superior products. Our perspective is to furnish outstanding captivating services.</p>
                        <p class="mb-5">We are a fast-growing company, but we have never lost sight of our core values. We believe in collaboration, innovation, and customer satisfaction. We are always looking for new ways to improve our products and services.</p>
                        <div class="row gy-4 gy-md-0 gx-xxl-5X">
                            <div class="col-12 col-md-6">
                                <div class="d-flex">
                                    <div class="me-4 text-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                            <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                                        </svg>
                                    </div>
                                    <div>
                                        <h2 class="h4 mb-3">Versatile Brand</h2>
                                        <p class="text-secondary mb-0">We are crafting a digital method that subsists life across all mediums.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="d-flex">
                                    <div class="me-4 text-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-fire" viewBox="0 0 16 16">
                                            <path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z" />
                                        </svg>
                                    </div>
                                    <div>
                                        <h2 class="h4 mb-3">Digital Agency</h2>
                                        <p class="text-secondary mb-0">We believe in innovation by merging primary with elaborate ideas.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</section>
</body>

Website1/Views/Contact/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/contact.css" />
</head>
<body>
    <section class="pictureOne">
        <div class="ptext1">
            <span class="text">Paralax Website</span>
        </div>
    </section>
    <section class="details">
        <div class="grid-container">
            <div class="grid-item">
                <p>Contact Us</p>
                <h3>Get In Touch</h3>
                <br />
                <p>Hi Therr kksd sodbso sv ssv  s</p>
                <br />
                <p><b> kuubsdkbvso snvosdh vdo osd so sdo os </b></p>


            </div>
            <div class="grid-item">
                <h3>Send Us A Message</h3>
                <form asp-controller="Contact" asp-action="Submit" method="post">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter your name">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" placeholder="name@example.com">
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" rows="3" placeholder="Enter your message"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
        </div>
    </section>
    <section class="map">
        <div class="pic">
            <img src="~/images/Map.jpg" />
        </div>
    </section>
    <section class="email-subscribe">
        <div class="grid-container">
            <div class="grid-item">
                <h1 class="NewsH1">NewsLetter</h1>
                <p class="Newsp">Sign up for our monthly newsletter to the latest news About Paralax </p>
            </div>
            <div class="grid-item">
                <br />
                <div class="input-group">
                    <input type="email" class="form-control rounded" placeholder="Enter Your Mail" aria-label="Search" aria-describedby="search-addon" />
                    <button type="button" class="btn btn-outline-primary" data-mdb-ripple-init>Subscribe</button>
                </div>
            </div>
        </div>
    </section>
    <section class="LastPart">

    </section>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="popup">
            <h2>Thank you for your submission!</h2>
            <p>@TempData["SuccessMessage"]</p>
        </div>
    }
    <!-- Scripts if needed -->
</body>
</html>

Website1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Paralax WebSite";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/Style.css" />
</head>
<body>
    <section class="pictureOne">
        <div class="ptext1">
            <span class="text">Paralax Website</span>
        </div>
    </section>
    <section class="description">
        <h2>Section One</h2>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione eveniet accusamus veniam fugiat similique illum corrupti qui in adipisci architecto distinctio, laboriosam deleniti beatae provident sed dolorum aspernatur sunt officia.</p>
    </section>
    <section class="pictureTwo">
        <div class="ptext1">
            <span class="text2">Explore Nature</span>
        </div>
    </section>
    <section class="description2">
        <h2>Section Two</h2>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione eveniet accusamus veniam fugiat similique illum corrupti qui in adipisci architecto distinctio, laboriosam deleniti beatae provident sed dolorum aspernatur sunt officia.</p>
    </section>
    <section class="pictureThree">
        <div class="ptext1">
            <span class="text3">Look Deep Into Nature</span>
        </div>
    </section>
    <section class="description3">
        <h2>Section Three</h2>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione eveniet accusamus veniam fugiat similique illum corrupti qui in adipisci architecto distinctio, laboriosam deleniti beatae provident sed dolorum aspernatur sunt officia.</p>
    </section>
    <section class="picturelast">
        <div class="ptext1">
            <span class="text">Thank You For Visisting</span>
        </div>
    </section>

    <!-- Scripts if needed -->
</body>
</html>

Website1/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/contact.css" />
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Website1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">ABOUT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark mr-7" asp-area="" asp-controller="Service" asp-action="Service">SERVICE</a>
                    </li>
                    @* <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li> *@
                    <br />
                    <li class="nav-item ml-5">
                    <li class="nav-item">
                        <input type="search" id="form1" class="form-control" />

                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary" data-mdb-ripple-init>
                            <i class="fas fa-search">Search</i>
                        </button>
                    </li>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</head>
<body>
    <style>
        .Login-From{
            min-height: 600px;
            margin-top: 133px;
        }
        }
    </style>
    <section class="pictureOne">
        <div class="ptext1">
            <span class="text">Paralax Website</span>
        </div>
    </section>
    <section class="Login-From">
        <section class="container">

            <form>
                <!-- Email input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <input type="email" id="form2Example1" class="form-control" />
                    <label class="form-label" for="form2Example1">Email address</label>
                </div>

                <!-- Password input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <input type="password" id="form2Example2" class="form-control" />
                    <label class="form-label" for="form2Example2">Password</label>
                </div>

                <!-- 2 column grid layout for inline styling -->
                <div class="row mb-4">
                    <div class="col d-flex">
                        <!-- Checkbox -->
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                            <label class="form-check-label" for="form2Example31"> Remember me </label>
                        </div>
                    </div>

                    <div class="col">
                        <!-- Simple link -->
                        <a href="#!">Forgot password?</a>
                    </div>
                </div>

                <!-- Submit button -->
                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Sign in</button>

                <!-- Register buttons -->
                <div class="text-center">
                    <p>Not a member? <a asp-area="" asp-controller="Home" asp-action="Register">Register</a></p>
                    <p>or sign In with:</p>
                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: blue;">
                        <i class="fab fa-facebook-f"></i>
                    </button>

                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: red;">
                        <i class="fab fa-google"></i>
                    </button>

                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: black;">
                        <i class="fab fa-twitter"></i>
                    </button>

                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle">
                        <i class="fab fa-github"></i>
                    </button>
                </div>


            </form>

        </section>
    </section>
</body>
</html>

Website1/Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

<!-- Section: Design Block -->
<section class="Signup-Form">
    <section class="text-center text-lg-start">
        <style>
            .cascading-right {
                margin-right: -50px;
            }

            media (max-width: 991.98px) {
                .cascading-right

            {
                margin-right: 0;
            }

            }

            .Signup-Form {
                margin-top: 55px;
            }
        </style>

        <!-- Jumbotron -->
        <div class="container py-4">
            <div class="row g-0 align-items-center">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="card cascading-right bg-body-tertiary" style="
            backdrop-filter: blur(30px);
            ">
                        <div class="card-body p-5 shadow-5 text-center">
                            <h2 class="fw-bold mb-5">Sign up now</h2>
                            <form>
                                <!-- 2 column grid layout with text inputs for the first and last names -->
                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div data-mdb-input-init class="form-outline">
                                            <input type="text" id="form3Example1" class="form-control" />
                                            <label class="form-label" for="form3Example1">First name</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-4">
                                        <div data-mdb-input-init class="form-outline">
                                            <input type="text" id="form3Example2" class="form-control" />
                                            <label class="form-label" for="form3Example2">Last name</label>
                                        </div>
                                    </div>
                                </div>

                                <!-- Email input -->
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="email" id="form3Example3" class="form-control" />
                                    <label class="form-label" for="form3Example3">Email address</label>
                                </div>

                                <!-- Password input -->
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="password" id="form3Example4" class="form-control" />
                                    <label class="form-label" for="form3Example4">Password</label>
                                </div>

                                <!-- Checkbox -->
                                <div class="form-check d-flex justify-content-center mb-4">
                                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                                    <label class="form-check-label" for="form2Example33">
                                        Subscribe to our newsletter
                                    </label>
                                </div>

                                <!-- Submit button -->
                                <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">
                                    Sign up
                                </button>

                                <!-- Register buttons -->
                                <div class="text-center">
                                    <p>or sign up with:</p>
                                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: blue;">
                                        <i class="fab fa-facebook-f"></i>
                                    </button>

                                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: red;">
                                        <i class="fab fa-google"></i>
                                    </button>

                                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle" style="background-color: black;">
                                        <i class="fab fa-twitter"></i>
                                    </button>

                                    <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1 rounded-circle">
                                        <i class="fab fa-github"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 mb-5 mb-lg-0">
                    <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
                         alt="" />
                </div>
            </div>
        </div>
        <!-- Jumbotron -->
    </section>
    <!-- Section: Design Block -->

</section>

Website1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Website1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Website1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">ABOUT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark mr-7" asp-area="" asp-controller="Service" asp-action="Service">SERVICE</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <br />
                        <li class="nav-item ml-5">
                        <li class="nav-item">
                            <input type="search" id="form1" class="form-control" />

                        </li>
                        <li class="nav-item">
                            <button type="button" class="btn btn-primary" data-mdb-ripple-init>
                                <i class="fas fa-search">Search</i>
                            </button>
                        </li>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-white" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Website1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        // Initialization for ES Users
        import { Input, Ripple, initMDB } from "mdb-ui-kit";

        initMDB({ Input, Ripple });</script>
</body>
</html>